// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {projects} from '../models';
import {main} from '../models';
import {store} from '../models';
import {diagnostics} from '../models';

export function AddRepository(arg1:string,arg2:string):Promise<projects.ProjectSummary>;

export function CreateProject(arg1:string,arg2:string):Promise<projects.ProjectSummary>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function DeleteProjectScans(arg1:string):Promise<void>;

export function ExportExceptions(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetDashboardAnalytics():Promise<main.DashboardAnalytics>;

export function GetExceptions(arg1:string):Promise<Array<store.Exception>>;

export function GetMetrics():Promise<main.Metrics>;

export function GetProjectFindings(arg1:string,arg2:string):Promise<Array<diagnostics.SecurityDiagnostic>>;

export function GetProjectScanHistory(arg1:string,arg2:number):Promise<Array<main.ScanHistory>>;

export function GetProjects():Promise<Array<projects.ProjectSummary>>;

export function ImportExceptions(arg1:string):Promise<void>;

export function RemoveException(arg1:string):Promise<void>;

export function RemoveRepository(arg1:string,arg2:string):Promise<projects.ProjectSummary>;

export function SelectDirectory():Promise<string>;

export function StartScan(arg1:string):Promise<void>;

export function SuppressFinding(arg1:string,arg2:diagnostics.SecurityDiagnostic,arg3:main.SuppressionOptions):Promise<void>;

export function UpdateProjectDetails(arg1:string,arg2:string,arg3:string,arg4:string):Promise<projects.ProjectSummary>;
