// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepository(arg1, arg2) {
  return window['go']['main']['App']['AddRepository'](arg1, arg2);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DeleteProjectScans(arg1) {
  return window['go']['main']['App']['DeleteProjectScans'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ExportExceptions(arg1) {
  return window['go']['main']['App']['ExportExceptions'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDashboardAnalytics() {
  return window['go']['main']['App']['GetDashboardAnalytics']();
}

export function GetExceptions(arg1) {
  return window['go']['main']['App']['GetExceptions'](arg1);
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetProjectFindings(arg1, arg2) {
  return window['go']['main']['App']['GetProjectFindings'](arg1, arg2);
}

export function GetProjectScanHistory(arg1, arg2) {
  return window['go']['main']['App']['GetProjectScanHistory'](arg1, arg2);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function ImportExceptions(arg1) {
  return window['go']['main']['App']['ImportExceptions'](arg1);
}

export function RemoveException(arg1) {
  return window['go']['main']['App']['RemoveException'](arg1);
}

export function RemoveRepository(arg1, arg2) {
  return window['go']['main']['App']['RemoveRepository'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function SuppressFinding(arg1, arg2, arg3) {
  return window['go']['main']['App']['SuppressFinding'](arg1, arg2, arg3);
}

export function UpdateProjectDetails(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProjectDetails'](arg1, arg2, arg3, arg4);
}
